config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :carts
  root "products#index"
  get "/products", to:'products#index'
  post '/add_to_cart/:product_id' => 'products#add_to_cart', :as => 'add_to_cart'
  delete '/remove_from_cart/:product_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items


    def add_item(product_id)
        product = Product.find(product_id)
        # cart = Cart.first
        self.products << product
    
    end
    
    def remove_item(product_id)
        cartitem = CartItem.where(product_id: product_id).first
        cartitem.destroy
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, :price, presence: true
    validates_numericality_of :price, greater_than: 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
   
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index      
      cart = Cart.first
      @cartitems = cart.products
      # render json: @cartitems
      # render json: @cartitems.as_json(only: [:title, :price])
      respond_to do |format|
         format.html # index.html.erb
         #format.xml  { render xml: @users }
         format.json { render json: @cartitems }
      end
    end 

      def remove_from_cart
        cart = Cart.first
        cart.remove_item(params[:product_id])  
        render json: {success: true}
     end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @products = Product.all
     respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @products }
      end
  end

  def add_to_cart
    cart = Cart.first
    cart.add_item(params[:product_id])
    render json: {success: true}
   # redirect_to carts_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<div class="container">
<h2><span class="badge badge-success">Cart</span></h2>
<table class="table table-dark">
  <thead class="thead-light">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% total_price = 0%>
  <% @cartitems.each do |item| %>
    <tr>
      <th scope="row"><%= item.id %></th>
      <td><%= item.title %></td>
      <td><%= item.price %>/-</td>
      <td><%= link_to "Remove", remove_from_cart_path(item),method: :delete, data: {confirm: "Are you sure?"},class:"btn btn-sm btn-outline-danger" %></td>
    </tr>
    <% total_price = total_price + item.price %>
    <% end %>
  </tbody>
</table>
<div class="container">
<button type="button" class="btn btn-outline-success btn-sm float-right">CHECKOUT</button>
<h3><span class="badge badge-secondary float-right">Cart Total: <%=total_price %></span></h3>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href=" "><h1> <span class="badge badge-primary">SHOPPING</span></h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <div class="container">
    <li class="nav-item">
     <%= link_to "Home", root_path, class:"btn btn-info" %>
    </li>
    </div>
    <div class="container">
    <li class="nav-item">
        <%= link_to "Cart", carts_path, class: "btn btn-info" %>
    </li>
    </div>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
<h2><span class="badge badge-success">Products</span></h2>
<table class="table table-dark">
  <thead class="thead-light">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <th scope="row"><%= product.id %></th>
      <td><%= product.title %></td>
      <td><%= product.price %>/-</td>
     <td><%= link_to "Add To Cart",add_to_cart_path(product), method: :post, class:"btn btn-sm btn-outline-warning" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>